# Generated by Django 5.1 on 2024-08-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='currency',
            field=models.CharField(blank=True, default='INR', max_length=255, null=True),
        ),
    ]
